Euv(e):= block([ans],
  local(la, be, su, E),
  tellsimp(E('v*'u), 0),
  tellsimp(E(1), 1),
  tellsimp(E('v^2), 1),
  tellsimp(E('u^2), su^2),
  declare([la, be, su], constant, E, linear),
  ans : ev(E(e), expand, infeval),
  remrule(E, all),
  ans);
x: be * v$
p: la * (x + u)$
P: x * (v - p)$
U: u * (v - p)$
%e0: diff(Euv(P), be);
%e1: Euv(P + U);

%so0: solve([%e1], [la])[1];

%so: solve([%e0, %e1], [la, be])[1];
